### ISSUE TITLE
Does upstream support via SOCKS5 proxy?

### ISSUE THREAD

**Issue by killbus** [compassd/dcompass#47]
Just like what the overture does.

Like:

```yaml
socks5Address: ip:port
```

**Comment by LEXUGE** [comment]
Not yet.

**Comment by LazyZhu** [comment]
The proxy support are most wanted since most dot and doh blocked now.

**Comment by LEXUGE** [comment]
I am still not sure about the details. What if domain names are involved in socks addresses? Do we have to have fallback resolution strategies?

**Comment by LEXUGE** [comment]
Support of socks5 is now part of the plan.

**Comment by LEXUGE** [comment]
socks5 and http are both supported in [the latest build](https://github.com/compassd/dcompass/releases/tag/build-20210730_1918) via the following syntax:
```yaml
cloudflare:
  https:
    uri: https://cloudflare-dns.com/dns-query
    addr: 1.1.1.1
    proxy: socks5://127.0.0.1:1080
```
If you have any question or issue regarding the proxy, please file another separate issue to illustrate.
