### ISSUE TITLE
[BUG] "hybrid" 的 upstream 抢先无应答时，不继续轮询其他 upstreams

### ISSUE THREAD

**Issue by killbus** [compassd/dcompass#69]
**Describe the bug 发生了什么**

`hybrid` 似乎是“谁快就返回”，即使没有有效的 DNS 记录。有没有办法可以继续轮询其他 upstreams？

**To Reproduce 如何重现**

完整配置：

```
---
verbosity: "info"
address: 0.0.0.0:53
table:
  start:
    if:
      domain:
        - file: /etc/dcompass/data/china.txt
    then:
      - query: domestic
      - end
    else:
      - dispatch
  dispatch:
    if: any
    then:
      - query:
          tag: internal
          cache_policy: disabled
      - check_internal
  check_internal:
    if:
      ipcidr:
        - /etc/dcompass/data/ipprivate.txt
    else:
      - query: secure
      - end
upstreams:
  DNSPod_A:
    https:
      no_sni: true
      uri: https://doh.pub/dns-query
      addr: 162.14.21.178
  DNSPod_B:
    https:
      no_sni: true
      uri: https://doh.pub/dns-query
      addr: 162.14.21.56
  Alidns_A:
    https:
      no_sni: true
      uri: https://dns.alidns.com/dns-query
      addr: 223.5.5.5
  Alidns_B:
    https:
      no_sni: true
      uri: https://dns.alidns.com/dns-query
      addr: 223.6.6.6
  internal_upstream_A:
    udp:
      addr: 192.168.1.99:53
      timeout: 1
  internal_upstream_B:
    udp:
      addr: 192.168.1.88:53
      timeout: 1
  domestic:
    hybrid:
      - DNSPod_A
      - DNSPod_B
      - Alidns_A
      - Alidns_B
  internal:
    hybrid:
      - internal_upstream_A
      - internal_upstream_B
  secure:
    https:
      no_sni: true
      uri: https://dns.google/dns-query
      addr: 8.8.8.8
```

我有两个 docker hosts 用作内部 upstreams。

```
  internal:
    hybrid:
      - internal_upstream_A
      - internal_upstream_B
```

测试某条 `仅 internal_upstream_B 能解析` 的内部记录 `internal.tld` 时，会随机无记录。猜测是 `internal_upstream_A` 已抢先完成响应？

`while true;do dig internal.tld @dcompass.host -p 53; done`

日志：

> 2021-08-06 17:06:07,241 INFO  [droute::router::table::rule] Domain "internal.tld" doesn't match at rule `start`
> 2021-08-06 17:06:07,241 INFO  [droute::router::table::rule] Domain "internal.tld" matches at rule `dispatch`
> 2021-08-06 17:06:07,241 INFO  [droute::router::upstreams::upstream] querying with upstream: internal_upstream_A
> 2021-08-06 17:06:07,242 INFO  [droute::router::upstreams::upstream] querying with upstream: internal_upstream_B
> 2021-08-06 17:06:07,245 INFO  [droute::router::upstreams::upstream] query successfully completed.
> 2021-08-06 17:06:07,245 INFO  [droute::router::table::rule] Domain "internal.tld" doesn't match at rule `check_internal`
> 2021-08-06 17:06:07,245 INFO  [droute::router::upstreams::upstream] querying with upstream: secure
> ...
> 2021-08-06 17:06:11,334 INFO  [droute::router::table::rule] Domain "internal.tld doesn't match at rule `start`
> 2021-08-06 17:06:11,335 INFO  [droute::router::table::rule] Domain "internal.tld" matches at rule `dispatch`
> 2021-08-06 17:06:11,335 INFO  [droute::router::upstreams::upstream] querying with upstream: internal_upstream_A
> 2021-08-06 17:06:11,335 INFO  [droute::router::upstreams::upstream] querying with upstream: internal_upstream_B
> 2021-08-06 17:06:11,337 INFO  [droute::router::upstreams::upstream] query successfully completed.
> 2021-08-06 17:06:11,337 INFO  [droute::router::table::rule] Domain "internal.tld" matches at rule `check_internal`
> 2021-08-06 17:06:11,337 INFO  [droute::router::table] Domain "internal.tld" has finished routing

如果这是 `Working as designed`，暂时只想到在 `table` 下套娃解决。

```table:
  ...
  dispatch:
    if: any
    then:
      - query:
          tag: internal_upstream_A
          cache_policy: disabled
      - check_internal_a
  check_internal_a:
    if:
      ipcidr:
        - /etc/dcompass/data/ipprivate.txt
    else:
      - query: internal_upstream_B
          cache_policy: disabled
      - check_internal_b
  check_internal_b:
    if:
      ipcidr:
        - /etc/dcompass/data/ipprivate.txt
    else:
      - query: secure
      - end
```

**Screenshots 截图**

**Version & Platform (please complete the following information) 版本信息**
 - Variant: `aarch64-unknown-linux-musl`
- OS: Linux
 - Version build-20210803_1007

**Additional context 附加信息**
