### ISSUE TITLE
[FEAT] qtype.rs define type 65 HTTPS or allow for INT values

### ISSUE THREAD

**Issue by bcookatpcsd** [compassd/dcompass#70]
https://en.wikipedia.org/wiki/List_of_DNS_record_types

iOS dns type HTTPS

Not DoH or DoT

Thank you sir.

**Comment by LEXUGE** [comment]
Sorry but I don't quite understand your question.
Speaking of qtype matcher's syntax, I recommend you take a look at the following related issue. https://github.com/compassd/dcompass/issues/65#issuecomment-890346598

**Comment by bcookatpcsd** [comment]
That does answer my question.

Not that I can read it ;) 

But the syntax of the code/config works.

Ty.

```
---
verbosity: info
cache_size: 4096
address: 192.0.192.1:53
table:
  start:
    if:
      domain:
      - file: "/etc/dnscrypt-proxy/blocked-names.txt"
    then:
    - blackhole
    - end
    else:
    - dispatch
  dispatch:
    if: any
    then:
    - query: secure
    - check_ipv6
  check_ipv6:
    if:
      qtype:
      - AAAA
      - INT: 65
    then:
    - blackhole
    - end
    else:
    - query: secure
    - end
upstreams:
  nextdns:
    https:
      no_sni: true
      uri: https://dns.nextdns.io/dns-query
      addr: 45.90.28.0
  plan9-doh:
    https:
      no_sni: true
      uri: https://hydra.plan9-ns1.com/dns-query
      addr: 173.199.126.35
  cloudflare:
    https:
      no_sni: true
      uri: https://cloudflare-dns.com/dns-query
      addr: 1.1.1.1
  quad9:
    https:
      no_sni: true
      uri: https://dns10.quad9.net/dns-query
      addr: 9.9.9.10
  google:
    https:
      no_sni: true
      uri: https://dns.google/dns-query
      addr: 8.8.8.8
  dnscrypt:
    udp:
      addr: 127.0.0.1:40
  secure:
    hybrid:
    - google
    - plan9-doh
    - quad9
    - nextdns-93fe46
    - cloudflare
    - dnscrypt
```
