### ISSUE TITLE
Type 65 HTTPS not defined..

### ISSUE THREAD

**Issue by bcookatpcsd** [compassd/dcompass#80]
https://en.wikipedia.org/wiki/List_of_DNS_record_types

[droute/src/router/table/rule/matchers/qtype.rs]

I also cannot figure out how to use the INT type(s) in this newer build.. 

```
./dcompass-x86_64-unknown-linux-gnu --config local.yml
Using the config file specified: local.yml
Error: unknown variant `HTTPS`, expected one of `A`, `NS`, `MD`, `MF`, `CNAME`, `SOA`, `MB`, `MG`, `MR`, `NULL`, `WKS`, `PTR`, `HINFO`, `MINFO`, `MX`, `TXT`, `RP`, `AFSDB`, `X25`, `ISDN`, `RT`, `NSAP`, `NSAPPTR`, `SIG`, `KEY`, `PX`, `GPOS`, `AAAA`, .. etc
```

```
    1	---
     2	verbosity: "info"
     3	address: 0.0.0.0:2053
     4	table:
     5	  start:
     6	    if: "qtype([AAAA, HTTPS])"
     7	    then:
     8	      - blackhole
     9	      - end
    10	    else:
    11	      - dispatch
    12	  dispatch:
    13	      - query: secure
    14	      - end
    15	
    16	upstreams:
    17	  doh-cloudflare:
    18	    https:
    19	      uri: https://cloudflare-dns.com/dns-query
    20	      addr: 1.1.1.1
    21	
    22	  doh-quad9:
    23	    https:
    24	      uri: https://dns.quad9.net/dns-query
    25	      addr: 9.9.9.9
    26	
    27	  dot-google:
    28	    tls:
    29	      domain: dns.google
    30	      addr: 8.8.8.8:853
    31	
    32	  secure:
    33	    hybrid:
    34	      - dot-google
    35	      - doh-cloudflare
    36	      - doh-quad9
```

If I use qtype([INT: 28]) instead of qtype([AAAA)] I get this error: 

Using the config file specified: local.yml
Error:  --> 1:11
  |
1 | qtype([INT: 28])
  |           ^---
  |
  = expected tuple

Thank you in advance.

**Comment by bcookatpcsd** [comment]
```
---
verbosity: "info"
address: 0.0.0.0:2053
table:
  start:
    if: "qtype([INT(28), INT(65)])"
    then:
      - blackhole
      - end
    else:
      - dispatch
  dispatch:
      - query: secure
      - end
```

Got it.. 

Needs some documentation or working example yml.. 

Thank you for all your work.
