### ISSUE TITLE
new config problem

### ISSUE THREAD

**Issue by bcookatpcsd** [compassd/dcompass#83]
I cannot figure out what the problem is.. 

/root/dcompass-x86_64-unknown-linux-gnu -c /etc/dcompass/quad9-adblock.yaml
Using the config file specified: /etc/dcompass/quad9-adblock.yaml
Error: Failed to parse the configuration file

Caused by:
    table: data did not match any variant of untagged enum RuleBuilders at line 5 column 8

```
---
verbosity: "debug"
address: 0.0.0.0:53
table:
  start:
    if: "qtype([INT(28), INT(65)])"
    then:
      - blackhole
      - end
    else:
      - dispatch
  dispatch:
    if:
      domain:
        - file: "/etc/dcompass/blocklist.txt"
    then:
      - blackhole
      - end
    else:
      - query: secure
      - end

upstreams:
  doh-quad9:
    https:
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
      sni: true

  dot-quad9:
    tls:
      domain: dns.quad9.net
      addr: 9.9.9.9:853
      sni: true

  secure:
    hybrid:
      - dot-quad9
      - doh-quad9

```

But this works without errors.. 

```
---
verbosity: "debug"
address: 0.0.0.0:53
table:
  start:
    if: "qtype([INT(28), INT(65)])"
    then:
      - blackhole
      - end
    else:
      - dispatch
  dispatch:
      - query: secure
      - end

upstreams:
  doh-quad9:
    https:
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
      sni: true

  dot-quad9:
    tls:
      domain: dns.quad9.net
      addr: 9.9.9.9:853
      sni: true

  secure:
    hybrid:
      - dot-quad9
      - doh-quad9
```

**Comment by bcookatpcsd** [comment]
The syntax is so hard.. 

This works.. 


```
---
verbosity: "debug"
address: 0.0.0.0:53

table:
  start:
    if: "qtype([INT(28), INT(65)])"
    then:
      - blackhole
      - end
    else:
      - dnsbl
  dnsbl:
    if: |
      domain([file("/etc/dcompass/blocklist.txt")])
    then:
      - blackhole
      - end
    else:
      - query: secure
      - end

upstreams:
  doh-quad9:
    https:
      uri: https://dns.quad9.net/dns-query
      addr: 9.9.9.9
      sni: true

  dot-quad9:
    tls:
      domain: dns.quad9.net
      addr: 9.9.9.9:853
      sni: true

  secure:
    hybrid:
      - dot-quad9
      - doh-quad9

```
