### ISSUE TITLE
[BUG] 缓存问题

### ISSUE THREAD

**Issue by aeeq** [compassd/dcompass#88]
**Describe the bug 发生了什么**
缓存不起作用,禁用和开启效果一样,用 dig 测试时间都是几十毫秒,缓存生效应该是 0ms吧

**To Reproduce 如何重现**
我的config
```
---
verbosity: "debug"
address: 0.0.0.0:2053
cache_size: 10000
table:
  start:
    if: "qtype([AAAA])"
    then:
      # A list of actions is allowed here
      - blackhole
      # The next tag to go
      - end
    else:
      - dispatch
  dispatch:
    - query:
       tag: domestic
       cache_policy: persistent
    - check_secure
  check_secure:
    if: |
      geoip(codes: ["CN"])
    else:
      - query:
         tag: secure
         cache_policy: persistent
      - end
upstreams:
  domestic:
    tls:
      addr: 1.12.12.12:853
      timeout: 1
      domain: dot.dns.pub
      sni: true
  secure:
    tls:
      timeout: 2
      addr: 8.8.4.4:853
      domain: dns.google
```

**Screenshots 截图**

![图片](https://user-images.githubusercontent.com/8926331/173019205-894f0a4b-bc87-45c3-92c9-8f3bfde58145.png)

**Version & Platform (please complete the following information) 版本信息**
 - Variant: [dcompass-x86_64-unknown-linux-gnu-full](https://github.com/compassd/dcompass/releases/download/build-20220316_1022/dcompass-x86_64-unknown-linux-gnu-full)
- OS: Windows 10
 - Version Automated build 20220316_1022

**Additional context 附加信息**
