### ISSUE TITLE
[BUG] dns 污染

### ISSUE THREAD

**Issue by echowings** [compassd/dcompass#89]
**Describe the bug 发生了什么**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1393341/177345262-66cdf4ee-750a-450b-ad95-838e37d7981d.png">
abs.twimg.com 被解析到facebook的地址，升级之前是没有的，加上script的代码，就出错了。
<img width="505" alt="image" src="https://user-images.githubusercontent.com/1393341/177345524-697d3dae-4534-4d5b-b297-89d882f971b7.png">

**To Reproduce 如何重现**

**Screenshots 截图**

**Version & Platform (please complete the following information) 版本信息**
 - Variant: amd64-unknown-linux-musl

- OS: [e.g. Linux]

**Additional context 附加信息**

**Comment by LEXUGE** [comment]
能提供一下完整的配置文件吗

**Comment by echowings** [comment]
> 能提供一下完整的配置文件吗

```yaml
---
verbosity: "info"
address: 0.0.0.0:53
script:
  init: |
    let geoip = new_builtin_geoip().seal();
  route: |
    // A few constants are predefined:
    // - query: the incoming query received
    // - ctx: the query context, e.g. client IP
    // - upstreams: the upstreams API
    if query.first_question.qtype == "AAAA" {
      return create_blackhole(query);
    }
    let resp = upstreams.send("domestic", query);
    try {
      let ans = resp.answer[0];
      return switch ans.rtype.to_string() {
        "A" if !geoip.contains(ans.to_a().ip, "CN") => { upstreams.send("secure", query) }
        "AAAA" if !geoip.contains(ans.to_aaaa().ip, "CN") => { upstreams.send("secure", query) }
        _ => resp
      };
    } catch(err) {
      print(err);
      return resp;
    }
upstreams:
  114DNS:
    udp:
      addr: 114.114.114.114:53

  Ali:
    udp:
      addr: 223.6.6.6:53

  domestic:
    hybrid:
      - 114DNS
      - Ali

  googledns1:
    udp:
      addr: 8.8.8.8:53
  googledns2:
    udp:
      addr: 8.8.4.4:53


  secure:
    hybrid:
      - googledns1
      - googledns2

 ```

**Comment by echowings** [comment]
你可以认为我的访问8.8.8.8/8.8.4.4没问题。 这个可能性请排除，因为直接设置8.8.8.8/8.8.4.4是没有问题的。

**Comment by echowings** [comment]
> 那剩余的可能性就是缓存污染，但是请求缓存是对于各个上游隔离的，我刚刚也再次确认了没有交叉污染。你可以告诉我 `dig www.twitter.com @8.8.8.8` 的结果吗？此外提供 `debug` 日志也可以帮助我找到问题所在。
> 
> 我的推测：
> 
> 1. 可以尝试不使用 hybrid 而是直接使用 8.8.8.8 / 8.8.4.4 的 **其中一个**，来避免其中一个对另一个造成污染。
> 2. 尝试其他连接方式，如果问题持续，问题则和上游设置无关。

```bash
MacBook-Pro >  dig abs.twimg.com 8.8.8.8

; <<>> DiG 9.10.6 <<>> abs.twimg.com 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57453
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;abs.twimg.com.			IN	A

;; ANSWER SECTION:
abs.twimg.com.		83	IN	CNAME	cs510.wpc.edgecastcdn.net.
cs510.wpc.edgecastcdn.net. 1846	IN	A	152.199.24.185

;; Query time: 172 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 06 16:01:47 CST 2022
;; MSG SIZE  rcvd: 97

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 33988
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;8.8.8.8.			IN	A

;; AUTHORITY SECTION:
.			86399	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022070600 1800 900 604800 86400

;; Query time: 171 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 06 16:01:47 CST 2022
;; MSG SIZE  rcvd: 111

MacBook-Pro > dig www.twitter.com 8.8.8.8

; <<>> DiG 9.10.6 <<>> www.twitter.com 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28015
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.twitter.com.		IN	A

;; ANSWER SECTION:
www.twitter.com.	433	IN	CNAME	twitter.com.
twitter.com.		1640	IN	A	104.244.42.1
twitter.com.		1640	IN	A	104.244.42.65

;; Query time: 171 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 06 16:01:58 CST 2022
;; MSG SIZE  rcvd: 90

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36642
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;8.8.8.8.			IN	A

;; AUTHORITY SECTION:
.			86393	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022070600 1800 900 604800 86400

;; Query time: 173 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jul 06 16:01:58 CST 2022
;; MSG SIZE  rcvd: 111
```

**Comment by LEXUGE** [comment]
问题所在应该是第一个 answer section 的 record 是 CNAME。而判断是否为中国 IP 时只会判断第一个 record 的 IP，导致 switch 判断时失败了。稍等一下我帮你改一下 script

**Comment by echowings** [comment]
```bash
/usr/local/bin/dcompass -c /etc/dcompass/config.yaml
Using the config file specified: /etc/dcompass/config.yaml
Error: Runtime error: An I/O error encountered. Check files provided for matcher(s) to ensure they exist and have the right permissions.
```

**Comment by LEXUGE** [comment]
我之前修改了一下 init 部分，你直接修改 route 部分就可以了
```yaml
---
verbosity: "info"
address: 0.0.0.0:53
script:
  init: |
    let geoip = new_builtin_geoip().seal();
  route: |
    // A few constants are predefined:
    // - query: the incoming query received
    // - ctx: the query context, e.g. client IP
    // - upstreams: the upstreams API
    if query.first_question.qtype == "AAAA" {
      return create_blackhole(query);
    }
    let resp = upstreams.send("domestic", query);

    for ans in resp.answer {
    switch ans.rtype.to_string() {
      "A" if !geoip.contains(ans.to_a().ip, "CN") => { return upstreams.send("secure", query); }
      "AAAA" if !geoip.contains(ans.to_aaaa().ip, "CN") => { return upstreams.send("secure", query); }
      _ => continue,
    };
    }
    resp
upstreams:
  114DNS:
    udp:
      addr: 114.114.114.114:53

  Ali:
    udp:
      addr: 223.6.6.6:53

  domestic:
    hybrid:
      - 114DNS
      - Ali

  googledns1:
    udp:
      addr: 8.8.8.8:53
  googledns2:
    udp:
      addr: 8.8.4.4:53


  secure:
    hybrid:
      - googledns1
      - googledns2
```
