### ISSUE TITLE
[BUG] 解析请求并发太多，导致dcompass服务假死

### ISSUE THREAD

**Issue by jame687** [compassd/dcompass#91]
您好

今天我在centos7.9搭建了dcompass 0.2.0-alpha.1，配置文件是加载example.yaml差不多的yaml文件

如果每秒请求几个解析请求程序运行一直正常

后面我把业务流量从smartdns切到dcompass后，不到几秒就看不到debug输出日志了，我手动测试解析也是提示DNS request timed out

是不是如果同时有几百条并发的解析请求，dcompass很容易不在工作

我应该如何优化呢？

谢谢

**Comment by LEXUGE** [comment]
我在本地使用 DNSPerf 测试应该是没有假死的问题的，可以给我看一下你的配置吗？

假死的问题上可能和 cache size，timeout 以及（如果使用了 DoT 的话）的 reuse timeout 等有关

**Comment by jame687** [comment]
您好

下面是我的配置文件

---
verbosity: "info"
address: 0.0.0.0:2053
script:
  init: |
    let geoip = new_builtin_geoip().seal();
  route: |
    // A few constants are predefined:
    // - query: the incoming query received
    // - ctx: the query context, e.g. client IP
    // - upstreams: the upstreams API
    let resp = upstreams.send("domestic", query);
    for ans in resp.answer {
      switch ans.rtype.to_string() {
        "A" if geoip.contains(ans.to_a().ip, "CN") => { return upstreams.send("secure", query); }
        "AAAA" if geoip.contains(ans.to_aaaa().ip, "CN") => { return upstreams.send("secure", query); }
        _ => continue,
      };
    }
    resp
upstreams:
  Google:
    udp:
      addr: 8.8.8.8:53

  Cloudfire:
    udp:
      addr: 1.1.1.1:53

  domestic:
    hybrid:
      - Google
      - Cloudfire


  114DNS:
    udp:
      addr: 114.114.114.114:53

  secure:
    hybrid:
      - 114DNS

我并没有设置相关的 cache size，timeout 

我从smaredns切换到dcompass，dcompass一开始几秒显示出几十条解析日志，后面过了几秒就完全卡着不动了

我需要加哪些参数呢？

谢谢

**Comment by LEXUGE** [comment]
我本地测试使用你的配置是没有假死的。

我的几种猜测：
1. musl 造成的性能问题，尝试使用 gnu-full 版本，如果 glibc 不匹配可以尝试本地编译
2. UDP 造成的性能问题，尝试使用 DNS over TLS 解决
3. 使用 ratelimit 来降低负载：`ratelimit: 150` 添加在 top-level

**Comment by LEXUGE** [comment]
使用 DoT 时可以参考以下参数：
```yaml
ali:
  tls:
    domain: "dns.alidns.com"
    max_reuse: 100
    reuse_timeout: 5000
    addr: "223.6.6.6:853"
```

**Comment by LEXUGE** [comment]
此外你的配置中 `domestic` 和 `secure` 的角色相反了，且 secure 的配置不当：domestic 是国内的 DNS 服务器，而 secure 是未污染的 DNS 源；你的 Google 和 Cloudflare 均使用了 UDP 协议，会被污染。

**Comment by LEXUGE** [comment]
![image](https://user-images.githubusercontent.com/13804737/188476118-67c34e45-d5c6-4eca-81ef-5d65c6b7386b.png)
全部替换为 Ali 的 DoT 后 perf 如下，你可以看看你那里是不是能复现：
```yaml
verbosity: "info"
address: 0.0.0.0:2053
script:
  init: |
    let geoip = new_builtin_geoip().seal();
  route: |
    // A few constants are predefined:
    // - query: the incoming query received
    // - ctx: the query context, e.g. client IP
    // - upstreams: the upstreams API
    let resp = upstreams.send("domestic", query);
    for ans in resp.answer {
      switch ans.rtype.to_string() {
        "A" if geoip.contains(ans.to_a().ip, "CN") => { return upstreams.send("domestic", query); }
        "AAAA" if geoip.contains(ans.to_aaaa().ip, "CN") => { return upstreams.send("domestic", query); }
        _ => continue,
      };
    }
    resp
upstreams:
  ali:
    tls:
      domain: "dns.alidns.com"
      max_reuse: 100
      reuse_timeout: 5000
      addr: "223.6.6.6:853"

  domestic:
    hybrid:
      - ali
```
